### ISSUE TITLE
Docs request: `pre-commit` config for `flake8`

### ISSUE THREAD

**Issue by jamesbraza** [jsh9/pydoclint#101]
```yaml
    - repo: https://github.com/jsh9/pydoclint
      rev: 0.3.8
      hooks:
          - id: pydoclint
            additional_dependencies: [flake8]
```

This is a possible config for using `pydoclint` as a `flake8`-plugin, via `pre-commit`.  However, it doesn't work, `noqa` comments aren't being respected.

This is the correct way:

```yaml
    - repo: https://github.com/pycqa/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
            args: [--toml-config=pyproject.toml]
            additional_dependencies:
                - Flake8-pyproject>=1.2.0 # For --toml-config
                - pydoclint
```

With the `pyproject.toml:

```toml
[tool.flake8]
allow-init-docstring = true
arg-type-hints-in-docstring = false
check-return-types = false
style = "google"
```

Can we add this to the docs? Notably, [`Flake8-pyproject`](https://github.com/john-hen/Flake8-pyproject) is key to keep using TOML config.
