### ISSUE TITLE
Failure to detect `noqa` statement

### ISSUE THREAD

**Issue by ddelange** [jsh9/pydoclint#109]
From https://github.com/jsh9/pydoclint/issues/108:
```py
import typing as tt

def read_jsonl(
    path_jsonl: str,
) -> tt.Iterator[dict[int, tuple[int, int, int]]]:
    """Read a jsonl file, one record at a time.

    Args:
        path_jsonl: Path to a jsonl file.

    Yields:
        One record.
    """
    with Path(path_jsonl).open("rb") as fp:
        yield from fp
```

Will flag false positives:
```
    29: DOC201: Function `mock_loop_over_video` does not have a return section in docstring
    29: DOC403: Function `mock_loop_over_video` has a "Yields" section in the docstring, but there are no "yield" statements, or the return annotation is not a Generator/Iterator/Iterable.
```

I tried to silence them with a noqa:

```py
import typing as tt

def read_jsonl(  # noqa: DOC201, DOC403, RUF100 false positives ref https://github.com/jsh9/pydoclint/issues/108
    path_jsonl: str,
) -> tt.Iterator[dict[int, tuple[int, int, int]]]:
    """Read a jsonl file, one record at a time.

    Args:
        path_jsonl: Path to a jsonl file.

    Yields:
        One record.
    """
    with Path(path_jsonl).open("rb") as fp:
        yield from fp
```

But that still flags the same false positives.

Using pre-commit hook:
```yaml
- repo: https://github.com/jsh9/pydoclint
  rev: 0.3.8
  hooks:
  - id: pydoclint
```

With pyproject.toml:
```toml
[tool.pydoclint]
style = "google"
arg-type-hints-in-docstring = false
check-return-types = false
check-yield-types = false
```
