### ISSUE TITLE
Ignoring Rules like `DOC101` and `DOC103`

### ISSUE THREAD

**Issue by bbaabemhp** [jsh9/pydoclint#228]
Hi guys,

first of all thanks for the awesome library!

I wanted to ignore some rules by default (instead of always ignoring them in-line in code)

I tried out ignoring them in my `pyproject.toml` somehow, but without any luck:

```toml
[tool.pydoclint]
style = 'numpy'
ignore = ["DOC101","DOC103"]
```

Would be awesome to find a solution. Thanks!
